name: go

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.18"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -coverprofile=coverage.txt -v ./...
        env:
          ZHIPUAI_API_KEY: ${{secrets.ZHIPUAI_API_KEY}}
          TEST_KNOWLEDGE_ID: ${{secrets.TEST_KNOWLEDGE_ID}}

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
